### ISSUE TITLE
error in Docker build

### ISSUE THREAD

**Issue by rcemper** [NjekTt/ApacheLog-Dataset#1]
````
[dataset-apachelog]     Compile SUCCESS
[dataset-apachelog]     Activate START
[dataset-apachelog]     Configure START
Compilation started on 01/10/2022 19:24:59 with qualifiers 'cuk'
Compiling class dc.data.teccod.promjetLog2021
Compiling table dc_data_teccod.promjetLog2021
Compiling routine dc.data.teccod.promjetLog2021.1
Detected 1 errors during compilation in 0.292s.
ERROR #9101: Global name 'dc.data.teccod.promjetLog2021.1.0' for 'DeferredIDLocation' is too long, must be no more than 31 characters in length.
  > ERROR #6084: Unknown errors detected, but no error code reported
````
But is has no impact to the generated class, data are loaded

**Comment by vberkutovv** [comment]
> ```
> [dataset-apachelog]     Compile SUCCESS
> [dataset-apachelog]     Activate START
> [dataset-apachelog]     Configure START
> Compilation started on 01/10/2022 19:24:59 with qualifiers 'cuk'
> Compiling class dc.data.teccod.promjetLog2021
> Compiling table dc_data_teccod.promjetLog2021
> Compiling routine dc.data.teccod.promjetLog2021.1
> Detected 1 errors during compilation in 0.292s.
> ERROR #9101: Global name 'dc.data.teccod.promjetLog2021.1.0' for 'DeferredIDLocation' is too long, must be no more than 31 characters in length.
>   > ERROR #6084: Unknown errors detected, but no error code reported
> ```
> 
> But is has no impact to the generated class, data are loaded

Corrected! Please update the package

**Comment by rcemper** [comment]
fixed
