### ISSUE TITLE
Local Demo fails

### ISSUE THREAD

**Issue by rcemper** [NjekTt/ApacheLog-Dataset#3]
dsw is not installed
http://localhost:32792/dsw/index.html#/IRISAPP/Dashboard/Apache%20Log%20example.dashboard
gives no result
**Not Found**
The requested URL /dsw/index.html was not found on this server.

**Comment by vberkutovv** [comment]
> dsw is not installed http://localhost:32792/dsw/index.html#/IRISAPP/Dashboard/Apache%20Log%20example.dashboard gives no result **Not Found** The requested URL /dsw/index.html was not found on this server.

Sorry, I didn't write the description correctly, this link is http://localhost:32792/dsw/index.html#/IRISAPP/Dashboard/Apache% 20Log%20example.dashboard refers to the package https://openexchange.intersystems.com/package/promjet-stats.

**Comment by rcemper** [comment]
my point is that ther is just no /dsw... inside the generated container.

**Comment by vberkutovv** [comment]
This application does not use dsw. Dsw is used in the dataset usage example in the https://openexchange.intersystems.com/package/promjet-stats package.

**Comment by rcemper** [comment]
AHHH!
sorry, I lost track with this endless long line  !
